output_config:
  name: 'dummy_modality'
  base_data: '../data/'
  output_dir: '../results/'
  copy_reference_data: False
  copy_reference_path: ""
  sample_filter:
    - 'filter_hc_mdd'

pipelines:
  skip: False
  types:
    - 'SVMPipeline'
    - 'RandomForestPipeline'
    - 'LogisticRegressionPipeline'
    - 'BoostingPipeline'
    - 'NaiveBayesPipeline'
    - 'KNNPipeline'
  redo: False
  n_processes: 1
  is_imbalanced_data: False