output_config:
  name: 'prs'
  base_data: '../raw_data/'
  output_dir: '../results_hc_mdd/'
  copy_reference_data: False
  sample_filter:
    - 'filter_hc_mdd'

pipelines:
  skip: False
  types:
    - 'UnivariateLogisticRegressionPipeline'
  redo: True
  n_processes: 5
  is_imbalanced_data: False
