output_config:
  name: 'social_support'
  base_data: '../raw_data/'
  output_dir: '../results/'
  copy_reference_data: False
  sample_filter:
    - 'filter_hc_mdd'

pipelines:
  skip: False
  types:
    - 'UnivariateLogisticRegressionPipeline'
  redo: True
  n_processes: 1
  is_imbalanced_data: False
